modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"

[[mods]]
modId="floral_flair"
version="${file.jarVersion}"
displayName="Floral Flair"
logoFile="floral.png"
description='''
A mod that adds lovely new flowers to your Minecraft world!
'''
[[dependencies.floral_flair]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.floral_flair]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.floral_flair]]
    modId = "blueprint"
mandatory = true
    versionRange = "[1.20.1-7.0.0,)"
    ordering = "BEFORE"
    side = "BOTH"