modLoader="javafml"
loaderVersion="[40,)"
license="Apache-2.0"

[[mods]]
modId="floral_flair"
version="${file.jarVersion}"
displayName="Floral Flair"
logoFile="floral.png"
description='''
A mod that adds lovely new flowers to your minecraft world!
'''
[[dependencies.floral_flair]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.floral_flair]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.floral_flair]]
    modId = "blueprint"
mandatory = true
    versionRange = "[1.18.2-5.2.0,)"
    ordering = "BEFORE"
    side = "BOTH"